spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/security?serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: xxx
    password: xxx
  redis:
    host: xxx
    password: xxx
    port: 6379


#配置日志所有的SQL都是不可见的，所以在后台是希望看到SQL是怎么执行的，就必须要配置日志。
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
